package wordpress

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/open-panel/open-panel/internal/models"
	"github.com/open-panel/open-panel/internal/services/php"
	sslpkg "github.com/open-panel/open-panel/internal/services/ssl"
)

// WordPressRewriteRules is stored on linked Website records for panel display;
// actual vhost is always generated by writeNginxVhost.
const WordPressRewriteRules = `# WordPress 伪静态
location / {
    try_files $uri $uri/ /index.php?$args;
}`

func (s *Service) writeNginxVhost(site *models.WordPressSite) (string, error) {
	confDir := filepath.Join(s.dataDir, "nginx", "vhosts")
	_ = os.MkdirAll(confDir, 0755)
	confPath := filepath.Join(confDir, site.Domain+".conf")
	root := filepath.ToSlash(site.RootPath)
	fastcgi := s.phpFastCGIBackend(site.PhpVersion)
	serverNames := strings.Join(s.allServerNames(site), " ")
	accessLog := filepath.ToSlash(filepath.Join(s.dataDir, "logs", site.Domain+"_access.log"))
	errorLog := filepath.ToSlash(filepath.Join(s.dataDir, "logs", site.Domain+"_error.log"))

	sslOn := s.siteSSLEnabled(site)
	cfCDN := site.CloudflareCDN
	var blocks []string
	switch {
	case cfCDN:
		blocks = append(blocks, wpHTTPSSLFrontBlock(serverNames, root, accessLog, errorLog, fastcgi))
		if sslOn {
			if sslBlock := s.wpHTTPSBlock(site, serverNames, root, accessLog, errorLog, fastcgi); sslBlock != "" {
				blocks = append(blocks, sslBlock)
			}
		}
	case sslOn:
		blocks = append(blocks, wpHTTPSSLFrontBlock(serverNames, root, accessLog, errorLog, fastcgi))
		if sslBlock := s.wpHTTPSBlock(site, serverNames, root, accessLog, errorLog, fastcgi); sslBlock != "" {
			blocks = append(blocks, sslBlock)
		} else {
			blocks = append(blocks, wpHTTPBlock(serverNames, root, accessLog, errorLog, fastcgi))
		}
	default:
		blocks = append(blocks, wpHTTPBlock(serverNames, root, accessLog, errorLog, fastcgi))
	}

	content := fmt.Sprintf("# Open Panel WordPress — %s\n# Bound domains: %s\n%s\n",
		site.Domain, serverNames, strings.Join(blocks, "\n"))
	if cfCDN {
		content = fmt.Sprintf("# Open Panel WordPress — %s (Cloudflare CDN mode)\n# Bound domains: %s\n%s\n",
			site.Domain, serverNames, strings.Join(blocks, "\n"))
	}
	_ = os.MkdirAll(filepath.Join(s.dataDir, "logs"), 0755)
	if err := os.WriteFile(confPath, []byte(content), 0644); err != nil {
		return "", err
	}
	return confPath, nil
}

func (s *Service) siteSSLEnabled(site *models.WordPressSite) bool {
	host := strings.TrimSpace(site.Domain)
	_, _, ok := sslpkg.CertPaths(s.dataDir, host)
	return ok
}

func wpHTTPBlock(serverNames, root, accessLog, errorLog, fastcgi string) string {
	return fmt.Sprintf(`server {
    listen 80;
    server_name %s;
    root %s;
    index index.php index.html;

    access_log %s;
    error_log %s;
%s
}`, serverNames, root, accessLog, errorLog, wpCommonLocations(fastcgi))
}

// wpHTTPSSLFrontBlock serves HTTP for CDN/proxy origins (e.g. Cloudflare Flexible SSL)
// while redirecting direct HTTP visitors to HTTPS.
func wpHTTPSSLFrontBlock(serverNames, root, accessLog, errorLog, fastcgi string) string {
	return fmt.Sprintf(`server {
    listen 80;
    server_name %s;
    root %s;
    index index.php index.html;

    access_log %s;
    error_log %s;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
    }
%s
}`, serverNames, root, accessLog, errorLog, wpCommonLocationsWithHTTPSRedirect(fastcgi))
}

func (s *Service) wpHTTPSBlock(site *models.WordPressSite, serverNames, root, accessLog, errorLog, fastcgi string) string {
	fullchain, privkey, ok := sslpkg.CertPaths(s.dataDir, site.Domain)
	if !ok {
		return ""
	}
	sslAccess := filepath.ToSlash(filepath.Join(s.dataDir, "logs", site.Domain+"_ssl_access.log"))
	sslError := filepath.ToSlash(filepath.Join(s.dataDir, "logs", site.Domain+"_ssl_error.log"))
	return fmt.Sprintf(`server {
    listen 443 ssl;
    server_name %s;
    root %s;
    index index.php index.html;

    ssl_certificate %s;
    ssl_certificate_key %s;

    access_log %s;
    error_log %s;
%s
}`, serverNames, root, filepath.ToSlash(fullchain), filepath.ToSlash(privkey), sslAccess, sslError, wpCommonLocations(fastcgi, "on"))
}

func wpCommonLocationsWithHTTPSRedirect(fastcgi string) string {
	httpsParams := `
        set $php_https "";
        if ($http_x_forwarded_proto = "https") {
            set $php_https "on";
        }
        if ($http_cf_ray != "") {
            set $php_https "on";
        }
        fastcgi_param HTTPS $php_https;`
	return fmt.Sprintf(`
    location / {
        set $require_https 1;
        if ($http_cf_ray != "") {
            set $require_https 0;
        }
        if ($http_x_forwarded_proto = "https") {
            set $require_https 0;
        }
        if ($require_https = 1) {
            return 301 https://$host$request_uri;
        }
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass %s;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;%s
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 7d;
        access_log off;
    }`, fastcgi, httpsParams)
}

func wpCommonLocations(fastcgi string, httpsMode ...string) string {
	mode := ""
	if len(httpsMode) > 0 {
		mode = httpsMode[0]
	}
	var httpsParams string
	switch mode {
	case "on":
		httpsParams = `
        fastcgi_param HTTPS on;`
	case "proxy":
		httpsParams = `
        set $php_https "";
        if ($http_x_forwarded_proto = "https") {
            set $php_https "on";
        }
        if ($http_cf_ray != "") {
            set $php_https "on";
        }
        fastcgi_param HTTPS $php_https;`
	default:
		httpsParams = `
        fastcgi_param HTTPS "";`
	}
	return fmt.Sprintf(`
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass %s;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;%s
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 7d;
        access_log off;
    }`, fastcgi, httpsParams)
}

func (s *Service) phpFastCGIBackend(version string) string {
	return php.FastCGIBackend(version)
}

func execNginxVersion() (string, error) {
	out, err := exec.Command("nginx", "-v").CombinedOutput()
	if err != nil {
		return "", err
	}
	line := strings.TrimSpace(string(out))
	if idx := strings.Index(line, "/"); idx >= 0 {
		return strings.TrimSpace(line[idx+1:]), nil
	}
	return line, nil
}

func reloadNginxIfAvailable() error {
	if runtime.GOOS == "windows" {
		return nil
	}
	if _, err := exec.LookPath("nginx"); err != nil {
		return nil
	}
	if err := exec.Command("nginx", "-t").Run(); err != nil {
		return err
	}
	return exec.Command("nginx", "-s", "reload").Run()
}
