package waf

type Country struct {
	Code string `json:"code"`
	Name string `json:"name"`
	Zh   string `json:"zh"`
}

func ListCountries() []Country {
	return []Country{
		{Code: "CN", Name: "China", Zh: "中国"},
		{Code: "HK", Name: "Hong Kong", Zh: "中国香港"},
		{Code: "MO", Name: "Macao", Zh: "中国澳门"},
		{Code: "TW", Name: "Taiwan", Zh: "中国台湾"},
		{Code: "US", Name: "United States", Zh: "美国"},
		{Code: "JP", Name: "Japan", Zh: "日本"},
		{Code: "KR", Name: "South Korea", Zh: "韩国"},
		{Code: "SG", Name: "Singapore", Zh: "新加坡"},
		{Code: "MY", Name: "Malaysia", Zh: "马来西亚"},
		{Code: "TH", Name: "Thailand", Zh: "泰国"},
		{Code: "VN", Name: "Vietnam", Zh: "越南"},
		{Code: "PH", Name: "Philippines", Zh: "菲律宾"},
		{Code: "ID", Name: "Indonesia", Zh: "印度尼西亚"},
		{Code: "IN", Name: "India", Zh: "印度"},
		{Code: "GB", Name: "United Kingdom", Zh: "英国"},
		{Code: "DE", Name: "Germany", Zh: "德国"},
		{Code: "FR", Name: "France", Zh: "法国"},
		{Code: "IT", Name: "Italy", Zh: "意大利"},
		{Code: "ES", Name: "Spain", Zh: "西班牙"},
		{Code: "NL", Name: "Netherlands", Zh: "荷兰"},
		{Code: "BE", Name: "Belgium", Zh: "比利时"},
		{Code: "CH", Name: "Switzerland", Zh: "瑞士"},
		{Code: "AT", Name: "Austria", Zh: "奥地利"},
		{Code: "SE", Name: "Sweden", Zh: "瑞典"},
		{Code: "NO", Name: "Norway", Zh: "挪威"},
		{Code: "DK", Name: "Denmark", Zh: "丹麦"},
		{Code: "FI", Name: "Finland", Zh: "芬兰"},
		{Code: "PL", Name: "Poland", Zh: "波兰"},
		{Code: "RU", Name: "Russia", Zh: "俄罗斯"},
		{Code: "UA", Name: "Ukraine", Zh: "乌克兰"},
		{Code: "TR", Name: "Turkey", Zh: "土耳其"},
		{Code: "SA", Name: "Saudi Arabia", Zh: "沙特阿拉伯"},
		{Code: "AE", Name: "United Arab Emirates", Zh: "阿联酋"},
		{Code: "IL", Name: "Israel", Zh: "以色列"},
		{Code: "IR", Name: "Iran", Zh: "伊朗"},
		{Code: "IQ", Name: "Iraq", Zh: "伊拉克"},
		{Code: "PK", Name: "Pakistan", Zh: "巴基斯坦"},
		{Code: "BD", Name: "Bangladesh", Zh: "孟加拉国"},
		{Code: "AU", Name: "Australia", Zh: "澳大利亚"},
		{Code: "NZ", Name: "New Zealand", Zh: "新西兰"},
		{Code: "CA", Name: "Canada", Zh: "加拿大"},
		{Code: "MX", Name: "Mexico", Zh: "墨西哥"},
		{Code: "BR", Name: "Brazil", Zh: "巴西"},
		{Code: "AR", Name: "Argentina", Zh: "阿根廷"},
		{Code: "CL", Name: "Chile", Zh: "智利"},
		{Code: "CO", Name: "Colombia", Zh: "哥伦比亚"},
		{Code: "ZA", Name: "South Africa", Zh: "南非"},
		{Code: "EG", Name: "Egypt", Zh: "埃及"},
		{Code: "NG", Name: "Nigeria", Zh: "尼日利亚"},
		{Code: "KE", Name: "Kenya", Zh: "肯尼亚"},
		{Code: "KP", Name: "North Korea", Zh: "朝鲜"},
		{Code: "KZ", Name: "Kazakhstan", Zh: "哈萨克斯坦"},
		{Code: "MM", Name: "Myanmar", Zh: "缅甸"},
		{Code: "KH", Name: "Cambodia", Zh: "柬埔寨"},
		{Code: "LA", Name: "Laos", Zh: "老挝"},
		{Code: "NP", Name: "Nepal", Zh: "尼泊尔"},
		{Code: "LK", Name: "Sri Lanka", Zh: "斯里兰卡"},
		{Code: "PT", Name: "Portugal", Zh: "葡萄牙"},
		{Code: "GR", Name: "Greece", Zh: "希腊"},
		{Code: "CZ", Name: "Czechia", Zh: "捷克"},
		{Code: "HU", Name: "Hungary", Zh: "匈牙利"},
		{Code: "RO", Name: "Romania", Zh: "罗马尼亚"},
		{Code: "BG", Name: "Bulgaria", Zh: "保加利亚"},
		{Code: "HR", Name: "Croatia", Zh: "克罗地亚"},
		{Code: "RS", Name: "Serbia", Zh: "塞尔维亚"},
		{Code: "SK", Name: "Slovakia", Zh: "斯洛伐克"},
		{Code: "SI", Name: "Slovenia", Zh: "斯洛文尼亚"},
		{Code: "IE", Name: "Ireland", Zh: "爱尔兰"},
		{Code: "LU", Name: "Luxembourg", Zh: "卢森堡"},
		{Code: "IS", Name: "Iceland", Zh: "冰岛"},
		{Code: "EE", Name: "Estonia", Zh: "爱沙尼亚"},
		{Code: "LV", Name: "Latvia", Zh: "拉脱维亚"},
		{Code: "LT", Name: "Lithuania", Zh: "立陶宛"},
		{Code: "BY", Name: "Belarus", Zh: "白俄罗斯"},
		{Code: "GE", Name: "Georgia", Zh: "格鲁吉亚"},
		{Code: "AZ", Name: "Azerbaijan", Zh: "阿塞拜疆"},
		{Code: "UZ", Name: "Uzbekistan", Zh: "乌兹别克斯坦"},
		{Code: "QA", Name: "Qatar", Zh: "卡塔尔"},
		{Code: "KW", Name: "Kuwait", Zh: "科威特"},
		{Code: "OM", Name: "Oman", Zh: "阿曼"},
		{Code: "BH", Name: "Bahrain", Zh: "巴林"},
		{Code: "JO", Name: "Jordan", Zh: "约旦"},
		{Code: "LB", Name: "Lebanon", Zh: "黎巴嫩"},
		{Code: "SY", Name: "Syria", Zh: "叙利亚"},
		{Code: "YE", Name: "Yemen", Zh: "也门"},
		{Code: "AF", Name: "Afghanistan", Zh: "阿富汗"},
		{Code: "MN", Name: "Mongolia", Zh: "蒙古"},
		{Code: "BN", Name: "Brunei", Zh: "文莱"},
		{Code: "TL", Name: "Timor-Leste", Zh: "东帝汶"},
		{Code: "PE", Name: "Peru", Zh: "秘鲁"},
		{Code: "VE", Name: "Venezuela", Zh: "委内瑞拉"},
		{Code: "EC", Name: "Ecuador", Zh: "厄瓜多尔"},
		{Code: "UY", Name: "Uruguay", Zh: "乌拉圭"},
		{Code: "PY", Name: "Paraguay", Zh: "巴拉圭"},
		{Code: "BO", Name: "Bolivia", Zh: "玻利维亚"},
		{Code: "CR", Name: "Costa Rica", Zh: "哥斯达黎加"},
		{Code: "PA", Name: "Panama", Zh: "巴拿马"},
		{Code: "CU", Name: "Cuba", Zh: "古巴"},
		{Code: "MA", Name: "Morocco", Zh: "摩洛哥"},
		{Code: "DZ", Name: "Algeria", Zh: "阿尔及利亚"},
		{Code: "TN", Name: "Tunisia", Zh: "突尼斯"},
		{Code: "LY", Name: "Libya", Zh: "利比亚"},
		{Code: "ET", Name: "Ethiopia", Zh: "埃塞俄比亚"},
		{Code: "GH", Name: "Ghana", Zh: "加纳"},
		{Code: "TZ", Name: "Tanzania", Zh: "坦桑尼亚"},
		{Code: "UG", Name: "Uganda", Zh: "乌干达"},
		{Code: "AO", Name: "Angola", Zh: "安哥拉"},
		{Code: "ZW", Name: "Zimbabwe", Zh: "津巴布韦"},
		{Code: "SD", Name: "Sudan", Zh: "苏丹"},
		{Code: "SN", Name: "Senegal", Zh: "塞内加尔"},
		{Code: "CI", Name: "Côte d'Ivoire", Zh: "科特迪瓦"},
		{Code: "CM", Name: "Cameroon", Zh: "喀麦隆"},
		{Code: "CD", Name: "DR Congo", Zh: "刚果(金)"},
		{Code: "CG", Name: "Congo", Zh: "刚果(布)"},
		{Code: "MU", Name: "Mauritius", Zh: "毛里求斯"},
		{Code: "RE", Name: "Réunion", Zh: "留尼汪"},
	}
}
